import Head from "next/head";
import Image from "components/Image";
import { useTheme } from "@emotion/react";
import Typography from "components/Typography";
import PageLayout from "layout/PageLayout";

export default function Home() {
  const theme = useTheme();
  return (
    <PageLayout>
      <Head>
        <title>Dolfinity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h1" color={theme.colors.deepBlue[0]}>
        제주 남방큰돌고래
      </Typography>
      <Typography variant="h1" color={theme.colors.deepBlue[0]}>
        deepBlue 5
      </Typography>
      <Typography variant="h1" color={theme.colors.deepBlue[0]}>
        deepBlue 8
      </Typography>
      <Typography variant="h1">h1</Typography>
      <Typography variant="h2">h2</Typography>
      <Typography variant="paragraph" color={theme.colors.deepBlue[0]}>
        paragraph
      </Typography>

      <Image src="/vercel.svg" alt="vercel" width="100px" height="100px" />
      <Image src="/vercel.svg" alt="vercel" width="100px" height="100px" blur />
    </PageLayout>
  );
}
