import Head from "next/head";
import Title from "components/Title";
import { Container } from "components/Container";
import Image from "components/Image";
import { useTheme } from "@emotion/react";
import Typography from "components/Typography";

export default function Home() {
  const theme = useTheme();
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title title="NextJS TypeScript Template" />
      <Typography variant="h1" color={theme.colors.deepBlue[1]}>
        deepBlue 1
      </Typography>
      <Typography variant="h1" color={theme.colors.deepBlue[5]}>
        deepBlue 5
      </Typography>
      <Typography variant="h1" color={theme.colors.deepBlue[8]}>
        deepBlue 8
      </Typography>
      <Typography variant="h1">h1</Typography>
      <Typography variant="h2">h2</Typography>
      <Typography variant="paragraph" color={theme.colors.deepBlue[1]}>
        paragraph
      </Typography>

      <Image src="/vercel.svg" alt="vercel" width="100px" height="100px" />
      <Image src="/vercel.svg" alt="vercel" width="100px" height="100px" blur />
    </Container>
  );
}
